version: '3.7'

services:
  stock_api:
    image: fiap-3soat-g15-stock-api:latest
    container_name: stock_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - stock_db
    environment:
      - DB_ENDPOINT=stock_db:5432
      - DB_NAME=selforder
      - DB_USERNAME=selforder
      - DB_PASSWORD=self@Order123!
      - ADMIN_ACCESS_TOKEN=token
    ports:
      - "8080:8080"
    restart: always

  stock_db:
    image: postgres:15.4
    container_name: stock_db
    volumes:
      - stock_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stock
      - POSTGRES_USER=selforder
      - POSTGRES_PASSWORD=self@Order123!
    ports:
      - "5432:5432"
    restart: always

volumes:
  stock_db:
    driver: local
