spring:
  application:
    name: stock-api
  datasource:
    url: jdbc:postgresql://${DB_ENDPOINT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: validate
        globally_quoted_identifiers: true

server:
  port: 8081

security:
  enable: false