package com.fiap.stock.application.domain.errors

enum class ErrorType {
    PRODUCT_NOT_FOUND,
    COMPONENT_NOT_FOUND,
    STOCK_NOT_FOUND,

    PRODUCT_NUMBER_IS_MANDATORY,
    COMPONENT_NUMBER_IS_MANDATORY,

    STOCK_ALREADY_EXISTS,

    INSUFFICIENT_STOCK,

    INVALID_PRODUCT_CATEGORY,

    UNEXPECTED_ERROR,
}
